#base   "../#alternatives/streamer mode/scripts/hudlayout.res"
#base	"../#alternatives/targetid/scripts/hudlayout.res"
#base   "../#alternatives/transparent viewmodels/scripts/hudlayout.res"
#base   "../#customizations/centered metal/scripts/hudlayout.res"
#base   "../#alternatives/game timers/scripts/hudlayout.res"
#base   "../#alternatives/lower spectator targetid/scripts/hudlayout.res"
#base   "../#alternatives/older targetid/scripts/hudlayout.res"
#base	"hudlayoutDefault.res"