#base   "../#customizations/#enabled/centered mvm money/scripts/hudlayout.res"
#base   "../#customizations/#enabled/cleaner buildings panels/scripts/hudlayout.res"
#base   "../#alternatives/#enabled/streamer mode/scripts/hudlayout.res"
#base	"../#alternatives/#enabled/targetid/scripts/hudlayout.res"
#base   "../#alternatives/#enabled/transparent viewmodels/scripts/hudlayout.res"
#base   "../#customizations/#enabled/centered metal/scripts/hudlayout.res"
#base   "../#alternatives/#enabled/game timers/scripts/hudlayout.res"
#base   "../#alternatives/#enabled/lower spectator targetid/scripts/hudlayout.res"
#base   "../#alternatives/#enabled/older targetid/scripts/hudlayout.res"
#base   "../_basetf2hud/scripts/hudlayout.res"
#base	"hudlayoutDefault.res"