#base	"../../#customizations/#enabled/class loadout panel options/resource/ui/classloadoutpanel.res"
#base	"../../#customizations/#enabled/more themed elements/resource/ui/classloadoutpanel.res"
#base	"../../#alternatives/#enabled/backpack & class loadout panels (left)/resource/ui/classloadoutpanel.res"
#base	"../../#alternatives/#enabled/backpack & class loadout panels (right)/resource/ui/classloadoutpanel.res"
#base	"../../_basetf2hud/resource/ui/classloadoutpanel.res"