#base   "../../#alternatives/#enabled/payload race panel/resource/ui/objectivestatusescort.res"
#base   "../../#customizations/#enabled/payload race panel v2/resource/ui/objectivestatusescort.res"
#base   "../../#customizations/#enabled/payload race panel/resource/ui/objectivestatusescort.res"
#base	"../../#alternatives/#enabled/payload panel/resource/ui/objectivestatusescort.res"
#base	"objectivestatusescortdefault.res"